### ISSUE TITLE
Update release notes

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-release-tools#10]

**Comment by marcingrzejszczak** [comment]
Let's think of how we could feed this with data. I don't really have an idea :P

**Comment by mp911de** [comment]
How about using Git as the source? You could derive from the version number, that is about to be released, the type of release (`M1`, `M2`, `RC1`, `RELEASE`, `x.RELEASE`) and the ancestor release. The previous release is usually tagged and we could inspect the commits with their messages that fall in between the tag and the head revision. Every commit containing a Github ticket reference can be used as release notes item.

**Comment by marcingrzejszczak** [comment]
In one of the companies that I was working we had sth similar but those release notes are very mechanical so to say. Sometimes you have a lot of commits in between releases. We could however find those commits that contain a "fixes" / "fixed" comment and put the summary of those. I wonder however if such release notes will bring any value.

**Comment by mp911de** [comment]
For Spring Data, every commit is associated with a ticket. I'm not saying to use all the commit messages as release notes. Rather checking whether a ticket is associated with the commit and if so, fetch the ticket description from Github (and maybe label) and put these into your release notes.

**Comment by marcingrzejszczak** [comment]
Yup - that could be a good idea. Any comments @spencergibb , @dsyer, @ryanjbaxter , @acole, @jkschneider ?

**Comment by dsyer** [comment]
The release notes tend to be very long and not very informative, if they are composed only of logs from git or github. I'm not a fan. I think a curated description of the main changes and migration notes work better (perhaps with a link to the milestone in github, which already has a list of tickets and links).

**Comment by marcingrzejszczak** [comment]
I think that such a list could serve as a basis for sth to change. We could produce a template (like with blog and email) from which someone could write the proper release notes?

**Comment by dsyer** [comment]
Yes, but you might as well make the template contain just a link to the milestone. There's no need to cluter it (or complicate its generation logic) with links to individual issues or commits.

**Comment by spencergibb** [comment]
I think a template is great.
