### ISSUE TITLE
RELEASER_PROJECTS_TO_SKIP list with spaces after comma doesn't fail

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-release-tools#112]
See https://jenkins.spring.io/view/Spring%20Cloud/view/Releaser/job/spring-cloud-meta-releaser/97/

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-jenkins-jobs/commit/5397d1bf32c146532117029ba7635c36db486df3
