### ISSUE TITLE
Meta-Releaser Per Release Train

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-release-tools#114]
Too many times is the initial configuration not right. There's no simple way to review it and make changes. Putting it in git and pulling from git will make this process easier.

**Comment by spencergibb** [comment]
I want it in source control with history

**Comment by marcingrzejszczak** [comment]
Maybe a branch in spring-cloud-release? With a property file with the name of the release? E.g. `hoxton.properties`

**Comment by spencergibb** [comment]
:+1:

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-jenkins-jobs/commit/96711c38880368da5d565e84b9093ec3d3f6ad61

**Comment by marcingrzejszczak** [comment]
Example of a property file - https://github.com/spring-cloud/spring-cloud-release/blob/jenkins-releaser-config/greenwich_build-snapshot.properties
