### ISSUE TITLE
Doc generation adds bogus version

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-release-tools#115]
- https://github.com/spring-cloud/spring-cloud-static/commit/a8de150b3479e26c0cc47f4d31b69f0ddacdd9aa 
- https://github.com/spring-cloud/spring-cloud-static/commit/6df82c6b8e52952edfd32e8dda963b58228cd5c0 
- https://github.com/spring-cloud/spring-cloud-static/commit/bd6bf60f9ec7dad9a1dbdbc1b7b421306fa9a1d3
- https://github.com/spring-cloud/spring-cloud-static/commit/a7173d3e1a9a57741667b8b11499ca061945811a

**Comment by spencergibb** [comment]
![image](https://user-images.githubusercontent.com/594085/49902441-f4e06780-fe31-11e8-9d21-acff716c71f6.png)

**Comment by ryanjbaxter** [comment]
seems like the version here is what influences the version displayed in the docs https://github.com/spring-cloud-samples/scripts/blob/master/docs/pom.xml#L16

**Comment by spencergibb** [comment]
Yup it used to be `1.3.5.BUILD-SNAPSHOT` prior to

https://github.com/spring-cloud-samples/scripts/commit/1403f3b01b75a405b7e10ad289ee47bdac36aba7#diff-48fabae9c2e321b2ab4d99057d5dc32eR8

**Comment by ryanjbaxter** [comment]
We could change it to `Greenwich.BUILD-SNAPSHOT` and have it match the release version (with some work via the meta-releaser I guess)

**Comment by spencergibb** [comment]
My guess is the thing that is inserting the version is using the wrong property. There are properties in that pom for the release train.

**Comment by ryanjbaxter** [comment]
maybe, I am sure @marcingrzejszczak knows for sure ;)

**Comment by ryanjbaxter** [comment]
The meta-releaser also appears to not be trying to generate the documentation, at least I couldnt see it in the Greenwich.RC2 release https://jenkins.spring.io/view/Spring%20Cloud/view/Releaser/job/spring-cloud-meta-releaser/107/consoleFull

**Comment by marcingrzejszczak** [comment]
That's fixed.
