### ISSUE TITLE
Update properties in projects to the lates build snapshot

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-cloud/spring-cloud-release-tools#120]
For instance, in spring-cloud-netflix we keep spring-cloud-commons version set as property:
`<spring-cloud-commons.version>2.0.3.BUILD-SNAPSHOT</spring-cloud-commons.version>` . After, spring-cloud-commons 2.0.3 is released, this property should be automatically bumped to `2.0.4.BUILD-SNAPSHOT`.

**Comment by dsyer** [comment]
This commit is broken in a similar way: https://github.com/spring-cloud/spring-cloud-function/commit/ad99b9b88bf21ead69a949037632378ede72699a#diff-1be34bd26c77feecdde5af1fb50acfac. The Spring Cloud Function version should be bumped and isn't.
