### ISSUE TITLE
Add Spring Cloud CLI to meta releaser

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-release-tools#129]
Needs to be released after Spring Cloud Release

**Comment by marcingrzejszczak** [comment]
We need to add it to https://github.com/spring-cloud/spring-cloud-release/tree/jenkins-releaser-config

**Comment by marcingrzejszczak** [comment]
Done https://github.com/spring-cloud/spring-cloud-release/commit/c48049166fa59ffa057c9c511e63cf295ce79968
