### ISSUE TITLE
Move Spring Cloud info to project agnostic service

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-release-tools#148]
The reasons why this project has been created apply to others and the current API could be changed to be made project agnostic. Sagan already has an API that provides some information per "project". For reference, here is the link for Spring Cloud: https://spring.io/project_metadata/spring-cloud

A few suggestions:

While not every projects have a notion of "Spring Boot", most of them do. In Spring Initializr we use the term "platformVersion" for that

`GET /springcloudversion/springboot/2.1.1.RELEASE` could be remapped to `GET /project_metadata/spring-cloud/versions?platformVersion=2.1.1.RELEASE`
`GET /bomversions/Finchley.SR1` could be remapped to `GET /project_metadata/spring-cloud/versions/Finchley.SR1`

Sagan has a notion of past milestones so it could be extended to have a notion of "upcoming milestones" that could show up in the same area.

There are use cases where Spring Initializr would like to get more insight about a particular Spring Boot version. So, something like `GET /project_metadata/spring-boot/versions/2.1.5.RELEASE` could give us the individual versions from the BOM (i.e. all `xyz-version` properties in the bom).

I am especially interested by the latter as we'd end up creating our own service for this which would be a shame considering the investment made in this one already. Moving it to sagan makes its access more ubiquitous and does not need a separate URI as well.

cc @bclozel

**Comment by ryanjbaxter** [comment]
@snicoll thanks.  This sounds reasonable to me.  I will bring this up at our team meeting tomorrow and report back here.

**Comment by ryanjbaxter** [comment]
@snicoll the team has no problem generalizing the API so we can accommodate other use cases

However we would be more comfortable if we move the project to its own repo in spring-io and then have Sagan (and any other future service) leverage it rather than make it part of Sagan.

**Comment by snicoll** [comment]
Thanks for the update. What is the problem of making it part of Sagan where the concept of project resides?

**Comment by ryanjbaxter** [comment]
I don't think that these APIs will exclusively be used by Sagan.  There might be other services that also end up using them.  We also don't want to be tied to Sagan.  If we want to add a new API that might be useful for Spring Cloud we don't want to have to redeploy Sagan to do that.

We also go the impression what we were trying to break up the monolith, so it seems to make sense that this would be its own service.

**Comment by snicoll** [comment]
Some misunderstanding here I think. It’s not about who uses it but where conceptually it is handled. My proposal is to tie that to the existing project concept which can already be used by anyone (initializr is using it to auto update the spring boot versions). As for the monolith side of things, it looks an unrelated concern to me. Sagan is already composed of multiple services.

The bottom line is that we already have a concept of projects in an existing HTTP api so I’d rather extend that than creating something on the side.

**Comment by ryanjbaxter** [comment]
I think we would rather it live outside of Sagan that is all.  I don't think anyone has any objection to generalizing the API.  That all makes sense.  We just want to be able to evolve the project independently of Sagan.  

Could we not move this project and the existing API(s) in Sagan to a new project and combine everything?

**Comment by spencergibb** [comment]
we've decided not to maintain the spring cloud info
