### ISSUE TITLE
during blog generation, github milestones are iterated over twice

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-release-tools#149]
Seems like once should be enough doing both checks at the same time. The second is for matching on tag, not sure what the first one is, but it routinely doesn't match.

**Comment by spencergibb** [comment]
`=== UPDATE RELEASE TRAIN WIKI ===` then re-executes the milestone search. Could likely be cached?

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-release-tools/commit/6efedbc324e4b94f21a6aa8bbf60dd9952009d48
