### ISSUE TITLE
run generate_readme.sh as part of release

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-release-tools#15]

**Comment by marcingrzejszczak** [comment]
What is this `generate_readme.sh` ? We're currently calling `./mvnw clean install -Pdocs`. The docs profile is already changing readme.

**Comment by spencergibb** [comment]
As far as I know the readme in the root is never updated unless `generate_readme.sh` is run.

**Comment by marcingrzejszczak** [comment]
Hmmm i don't think so. But maybe I'm wrong. I'll check it out tomorrow

**Comment by ryanjbaxter** [comment]
I agree with @marcingrzejszczak I thought it was generated when the `docs` profile was activated

**Comment by spencergibb** [comment]
Looks like you both are correct https://github.com/spring-cloud/spring-cloud-build/blob/74a746b71eb5c9260a5aba0c86a39e0ccf31c833/pom.xml#L672-L687
