### ISSUE TITLE
Create an issue in start.spring.io when a new release train is available

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-release-tools#153]
Just listing the new release train version and the Boot dependency would be enough to ensure that https://github.com/spring-io/start.spring.io is updated accurately and promptly.

**Comment by marcingrzejszczak** [comment]
A new version of the release train, correct?

**Comment by dsyer** [comment]
A new release of spring-cloud-dependencies, I guess, including milestones. Initializr hasn't been updated for Hoxton.M1, and it could have been, if we had created an issue.

**Comment by marcingrzejszczak** [comment]
We can try to do a pull request maybe?

**Comment by dsyer** [comment]
Automating a PR would be much harder (YAML diffs). Creating an issue is easy enough if we have a github token available, which we must have.

**Comment by marcingrzejszczak** [comment]
We already do exactly the same thing for the guides so we can do the same for start.spring.io

**Comment by spencergibb** [comment]
I created a pr for hoxton, just hasn't been merged
