### ISSUE TITLE
Add support for spring-cloud-cli

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-release-tools#16]
Might be hard since it's not part of the bom, but is a downstream project.

**Comment by marcingrzejszczak** [comment]
We could add the version via a property for example. Then it would be treated as if it came from `spring-cloud-release`. WDYT?

**Comment by spencergibb** [comment]
yeah, that would be fine. cli is a snowflake right now because its release is very different.

**Comment by marcingrzejszczak** [comment]
just set 

```
releaser.fixed-versions:
  spring-cloud-cli: 1.0.0.RELEASE
```
