### ISSUE TITLE
Do not create issues on start.spring.io for Spring Cloud Stream releases

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-release-tools#160]
start.spring.io only manages the spring cloud bom (that includes a number of spring cloud sub-projects).

I believe only the Spring Cloud release train is required [at this point](https://github.com/spring-io/start.spring.io/blob/d99c61fff20dedb3464d9ef2a53a2f8efbe1bf75/start-site/src/main/resources/application.yml#L46).

Maybe this can be used by third party releases though, Azure, GCP?

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-jenkins-jobs/commit/894cb39350715799d4e7b1ba6094b1682d124a8c
