### ISSUE TITLE
Do not create issue to upgrade on start.spring.io until the bits are available

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-release-tools#161]
A release process created an issue (https://github.com/spring-io/start.spring.io/issues/259) 12h ago and the bits aren't available.

I think it's confusing that an automated tool creates an upgrade issue for something that hasn't been validated as being available.

The sync to central could wait and check that the bits are available and create the issue once this has been validated.

**Comment by spencergibb** [comment]
this has been disabled
