### ISSUE TITLE
Publishing Release Train Docs Fails With Invalid Option

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-release-tools#164]
Publishing the release train docs failed for Hoxton.RC1 because we passed an invalid option
`Invalid option: [-Pmilestone]`
[consoleText.txt](https://github.com/spring-cloud/spring-cloud-release-tools/files/3769817/consoleText.txt)

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud-samples/scripts/commit/2b32278c586f06e53c6bbda2b23fed2f0365662e
