### ISSUE TITLE
Simplifying redirects for Spring Cloud docs

### ISSUE THREAD

**Issue by OlgaMaciaszek** [spring-cloud/spring-cloud-release-tools#165]
3 different pieces of infrastructure (and possibly issuing 2-3 HTTP redirects in a row) involved in Spring Cloud redirects.

As described by @bclozel :

> Since Spring Cloud is generating and publishing the docs on github, wouldn't it be possible to generate there a symlink, a redirect rule or an HTML page that issues the redirect?
> So worst case scenario (without a symlink) we'd get:
> https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/ -> https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/current/reference/html/ -> https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.0.RC1/reference/html/
 
> The redirect app has no knowledge of the project metadata, as it's separate from spring.io.
> The fact that we'd need to involve Apache httpd rules, the redirect app, spring.io itself and github pages, just to get the page of the current version makes me think we've re in trouble with our publishing model right now.

**Comment by olegz** [comment]
Just to give more context. . . Historically (across all spring projects) the `current` docs have always been available - https://docs.spring.io/{project-name}/docs/current/reference/htmlsingle/

Users actually bookmark it. Given that now we publish to s-c-static it is not reflected with such bookmarks and you can clearly see it here https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/  where it points to a very old version of SCSt

**Comment by marcingrzejszczak** [comment]
We will create a redirection page that will look like this

https://cloud.spring.io/spring-cloud-static/{project-name}/current/index.html

it will redirect to the latest available GA release
