### ISSUE TITLE
Release Train Docs Failed When Running Greenwich.SR4

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-release-tools#170]
`15:55:16 release_train.sh: line 359: pushd: commons: No such file or directory`

https://jenkins.spring.io/view/Spring%20Cloud/view/Releaser/job/spring-cloud-meta-releaser/259/console

**Comment by marcingrzejszczak** [comment]
fixed (hopefully) via 
- https://github.com/spring-cloud-samples/scripts/commit/2d94d2e244fff6391cd7bd1afb3198ba17ca2db6
- https://github.com/spring-cloud-samples/scripts/commit/979d21c455a3f94bd46e178e31602c4a0e8678de
