### ISSUE TITLE
{{nextVersion}} template is replaced by a bumped RELEASE instead of BUILD-SNAPSHOT

### ISSUE THREAD

**Issue by simonbasle** [spring-cloud/spring-cloud-release-tools#186]
in `ProjectCommandExecutor#replaceAllPlaceholders`, the `{{nextVersion}}` is documented to be "the upcoming snapshot to be used". Currently, the replacement code is:
```java
replace(NEXT_VERSION_MUSTACHE, changedVersion.bumpedVersion())
```

With an example of releasing `3.2.1.RELEASE`, the `originalVersion` would expected to be `3.2.1.BUILD-SNAPSHOT` (the current snapshot). `changedVersion` would be `3.2.1.RELEASE`.

Since `bumpedVersion()` only bumps the PATCH (not the SUFFIX), the `.RELEASE` suffix is maintained => we get `3.2.2.RELEASE` as `{{nextVersion}} 💥

`originalVersion` should instead be used:

```java
replace(NEXT_VERSION_MUSTACHE, original.bumpedVersion())
```
Would correctly yield `3.2.2.BUILD-SNAPSHOT`

**Comment by spencergibb** [comment]
I think I've noticed this before also.
