### ISSUE TITLE
Update spring.io

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-release-tools#22]
For releases and milestones, we can use the sagan api https://spring.io/docs/index.html to add the latest, {M*|RC*} or {RELEASE|SR*}.

**Comment by marcingrzejszczak** [comment]
Doe via https://github.com/spring-cloud/spring-cloud-release-tools/commit/b1e6c2f301e502a04f44057a9ec7b3fca7629f15

**Comment by marcingrzejszczak** [comment]
Currently we don't use Sagan for Milestones or Release Candidates (at least I don't see it) so it's going to work only for RELEASE / SR and SNAPSHOTs

**Comment by spencergibb** [comment]
I think it should support milestones and release candidates. We just haven't because it hasn't been automated.
