### ISSUE TITLE
Revert to snapshots selects wrong versions on s-c-commons

### ISSUE THREAD

**Issue by jkschneider** [spring-cloud/spring-cloud-release-tools#27]
For release 1.2.1.RELEASE, the s-c-commons version was reverted to 1.2.1.BUILD-SNAPSHOT rather than 1.2.2.BUILD-SNAPSHOT.

s-c-build was reverted from 1.3.2.RELEASE to 1.3.1.BUILD-SNAPSHOT.

**Comment by jkschneider** [comment]
Same problem on s-c-aws:

![image](https://cloud.githubusercontent.com/assets/1697736/26014527/879e9c0a-3722-11e7-9806-4c789a2b5df6.png)

**Comment by marcingrzejszczak** [comment]
Again I can't replicate it... maybe I've already fixed some bugs or sth

![releaser_27](https://cloud.githubusercontent.com/assets/3297437/26788280/08096aee-4a0d-11e7-9fb0-1ea7c17bcfc6.png)

**Comment by marcingrzejszczak** [comment]
Most likely got fixed in the meantime
