### ISSUE TITLE
Change version when there is a new release of this project

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-release-tools#28]
Multiple 'releases' have been made with the 1.0.0.M1 version.

**Comment by marcingrzejszczak** [comment]
Don't follow :/ can you explain that in more depth?

**Comment by spencergibb** [comment]
There have been over 100 commits and we still use version `1.0.0.M1` (it never changes) so I have no idea what is actually in M1. I always build locally and use that jar.

**Comment by marcingrzejszczak** [comment]
I didn't want to polute the report.spring.io with snapshot versions. Actually I build locally too - is faster than downloading the jar ;) I can start doing continuous deployment of the tool but I don't think it makes sense. Wdyt?

**Comment by spencergibb** [comment]
I don't know why not wanting to put snapshots in repo.spring.io is a reason not to use it.

**Comment by spencergibb** [comment]
We don't have to do continuous deployment, but then it shouldn't be an M1 and we should change the documentation.

**Comment by marcingrzejszczak** [comment]
It will be more difficult to download a snapshot jar with curl cause you need to provide the URL to a concrete version of the JAR

**Comment by spencergibb** [comment]
Sure, then it should be compile snapshots on your local box or release real milestones. The current process is neither and needs to change. Especially if both you and I are always compiling locally and not following the documentation.
