### ISSUE TITLE
Consider running release tools from jenkins rather than local machines

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-release-tools#30]
This would eliminate the building on our machines part.

GPG signing would need to be figured out.

/cc @marcingrzejszczak @dsyer @ryanjbaxter @jkschneider

**Comment by jkschneider** [comment]
I know this will probably get laughed down, but I have to at least say that if we release to Bintray/JCenter instead we can avoid GPG signing entirely AND guarantee that our releases get to Maven Central and JCenter simultaneously. Plus we won't have to go manually close repos at oss.sonatype.org anymore.

**Comment by spencergibb** [comment]
😜 
> I know this will probably get laughed down

Nah...

I'd love to hear reasons why not.

**Comment by marcingrzejszczak** [comment]
I think that the tool is not stable enough to move it to Jenkins for automated releasing... :/

**Comment by spencergibb** [comment]
But good enough for releasing without jenkins?

**Comment by marcingrzejszczak** [comment]
Yeah cause you can run it in a verbose mode so that you can check if each stop was done properly

**Comment by marcingrzejszczak** [comment]
- [ ] - setup Jenkins jobs
- [ ] - setup Jenkins configuration of keys

**Comment by marcingrzejszczak** [comment]
Setup created - now we're trying to make things work ;)
