### ISSUE TITLE
Add `.git` folder into list of ignored poms

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-release-tools#49]
When doing the release on Jenkins we clone the releaser into `.git` folder. The problem with that is that scan that repo to update poms (and we fail the build cause we're using snapshots). 

```
19:28:38 Caused by: java.lang.IllegalStateException: The file [/opt/jenkins/data/workspace/spring-cloud-commons-releaser/.git/releaser/spring-cloud-release-tools-spring/src/test/resources/projects/spring-cloud-release/spring-cloud-starter-parent/pom.xml] contains a BUILD-SNAPSHOT version for a non snapshot release in line number [23]
19:28:38 
19:28:38 		<spring-cloud.version>Dalston.BUILD-SNAPSHOT</spring-cloud.version>
```

That's why it broke your build @spencergibb

**Comment by spencergibb** [comment]
Seems odd to clone something into .git.

**Comment by marcingrzejszczak** [comment]
In our projects we need to clone the `releaser`. We can clone it to some temp directory but then we won't see the code in the workspace. We can't clone it to `target` cause it gets deleted. We can't clone it to any other dir in the root of the project cause we are commiting and pushing stuff so we would clone the releaser code. `.git` folder is by default excluded from any version control that's why I clone it there.

**Comment by spencergibb** [comment]
Why is a temp directory not an option? I don't understand.

**Comment by marcingrzejszczak** [comment]
It's an option but I'd have to modify the Jenkins scripts and if something goes wrong with the releaser build I won't be able to see the sources.

**Comment by marcingrzejszczak** [comment]
But if it's crucial for you so that the code gets cloned to `tmp` then I can do it, although I don't see a lot of benefit out of it.

**Comment by spencergibb** [comment]
Just trying to understand. The other option is to git ignore something else in each project, correct?

**Comment by marcingrzejszczak** [comment]
no no... Let's take a look at this. We're trying to release Sleuth. What we do first is that we clone Sleuth's code.

- workspace
  - Sleuth's `.git` 
  - Sleuth's code

Now we need to clone and build the releaser. We need to store it somewhere. Currently we do it like this

- workspace
  - Sleuth's `.git` 
    - releaser's code
  - Sleuth's code

I put it there cause I don't want it to be with Sleuth's code. We could `.gitignore` a `releaser` folder in each project but it's pointless and we will still have the same problem cause the releaser's logic is executed form the project's root. So all the releaser's poms will get updated since they lay in a subfolder of our project... 

So there are 2 options. 

1) Ignore `.git` from pom updating
2) Clone the releaser to tmp, build it there, call the releaser's JAR from the project's root. Then my fix will get ignored cause no releaser's code is anywhere near the project's path

**Comment by spencergibb** [comment]
Ok. Another question ;-) why are we cloning and building releaser?

**Comment by marcingrzejszczak** [comment]
Cause we need the jar and we're not publishing anything else but snapshots? At some point, you've asked me why I'm overriding the `1.0.0.M1` constantly. So the answer was that it's not a snapshot and I can download the latest version. So here, instead of rebuilding the releaser I could just download the jar but since we're not doing it I'm cloning and building it each time from scratch.
