### ISSUE TITLE
Spring Cloud Netflix build broken with releaser

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-release-tools#51]
Since it is now a two step build (build contract modules, then back to root and build). We've updated CI, but now I have to do things by hand.

**Comment by spencergibb** [comment]
I did the contract build my self, then am reruning releaser with `3-` option to build and run everything else.

**Comment by marcingrzejszczak** [comment]
Hmm you shouldn't be needing to do that. Just remember to run it with the `config` option.

```
$ java -jar ~/repo/spring-cloud-release-tools/spring-cloud-release-tools-spring/target/spring-cloud-release-tools-spring-1.0.0.BUILD-SNAPSHOT.jar --releaser.pom.branch=vDalston.SR1 --spring.config.name=releaser
```

It will automatically call the proper script - https://github.com/spring-cloud/spring-cloud-netflix/blob/master/config/releaser.yml#L3

**Comment by spencergibb** [comment]
Does the jenkins releaser do that?

**Comment by marcingrzejszczak** [comment]
yup https://github.com/spring-cloud/spring-cloud-jenkins-jobs/blob/master/src/main/groovy/org/springframework/jenkins/cloud/release/SpringCloudReleaseMaker.groovy#L85
