### ISSUE TITLE
notes.md issues

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-release-tools#53]
Link to milestones is wrong

- wrong: https://api.github.com/repos/spring-cloud/spring-cloud-sleuth/milestones/33
- correct: https://github.com/spring-cloud/spring-cloud-sleuth/milestone/33?closed=1

There are empty issues links if there wasn't a milestone.

**Comment by marcingrzejszczak** [comment]
> Link to milestones is wrong

That's already fixed - https://github.com/spring-cloud/spring-cloud-release-
tools/commit/8eb345fd0ba6696c0a3f84ef1c9b1737d47980b4

> There are empty issues links if there wasn't a milestone.

What else should we do then?

**Comment by spencergibb** [comment]
That commit doesn't seem to be related. This has nothing to do with sagan.

Not put an empty issues link?

**Comment by marcingrzejszczak** [comment]
> That commit doesn't seem to be related. This has nothing to do with sagan.

I fixed the link

**Comment by spencergibb** [comment]
it will still be incorrect, `s/milestones/milestone`

**Comment by marcingrzejszczak** [comment]
ehhhh... thanks for noticing that

**Comment by spencergibb** [comment]
NP, just did the search and replace a few minutes ago.
