### ISSUE TITLE
Simplify and document example command line in README

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-release-tools#65]
The first example command line is this:

```
$ java -jar ~/repo/spring-cloud-release-tools/spring-cloud-release-tools-spring/target/spring-cloud-release-tools-spring-1.0.0.BUILD-SNAPSHOT.jar --releaser.pom.branch=vDalston.SR1 --spring.config.name=releaser
```

The first argument is not explained (why do I need it, what would change if I made it into garbage?). the second argument isn't needed (it's optional and only useful if you have a config file called `releaser.yml`).

**Comment by marcingrzejszczak** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-release-tools/commit/981e5a1b50e4e0b024b38a3e3c8151c6e1627b5c
