### ISSUE TITLE
Empty pom.xml causes failure

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-release-tools#71]
This actually might be a good thing.

https://jenkins.spring.io/view/Spring%20Cloud/view/Releaser/job/spring-cloud-netflix-releaser/6/console

This is how I worked around the issue
https://github.com/spring-cloud/spring-cloud-netflix/commit/eec4c8cf85b6376a1176e34b133fa801fb50401d

**Comment by marcingrzejszczak** [comment]
Yeah, empty pom sounds like a bad idea ;P

**Comment by spencergibb** [comment]
I found four or five during the latest release. Maybe a clearer error message, since I had to explore.

**Comment by marcingrzejszczak** [comment]
Yeah, I'll try adding a test with a good message
