### ISSUE TITLE
Spring Cloud Config Release Job Fails On Jenkins Using 1.3.x

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-release-tools#73]
When trying to release the 1.3.x. branch of Spring Cloud Config the build is downloading artifacts from the snapshots repo on repo.spring.io instead of the releases repo.

https://jenkins.spring.io/view/Spring%20Cloud/view/Releaser/job/spring-cloud-config-releaser/7/

**Comment by ryanjbaxter** [comment]
Appears that Consul is suffering from the same problem https://jenkins.spring.io/view/Spring%20Cloud/view/Releaser/job/spring-cloud-consul-releaser/12/

**Comment by marcingrzejszczak** [comment]
Is it fixed? (https://jenkins.spring.io/view/Spring%20Cloud/view/Releaser/job/spring-cloud-consul-releaser/13/console) it looks green. What was the problem?
