### ISSUE TITLE
Spring Cloud Sleuth 2.0.0 Build Fails

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-release-tools#76]
https://jenkins.spring.io/view/Spring%20Cloud/view/Releaser/job/spring-cloud-sleuth-releaser/38/

**Comment by marcingrzejszczak** [comment]
Flakey tests or sth

**Comment by spencergibb** [comment]
Works everywhere else but jenkins

**Comment by marcingrzejszczak** [comment]
Done
