### ISSUE TITLE
Option to not submit guides upgrade ticket

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-release-tools#81]
Use this for Edgware SRs?

https://github.com/spring-guides/getting-started-guides/issues/69

**Comment by gregturn** [comment]
Keep the tickets coming. Just update your script to only do that for Finchley releases.

**Comment by spencergibb** [comment]
The script doesn't know about finchley vs edgware, hence an option to not submit, that the user has to set.

**Comment by marcingrzejszczak** [comment]
We will do it with the meta-release ticket I guess https://github.com/spring-cloud/spring-cloud-release-tools/issues/24 . We'll allow a set of properties for the whole release train

**Comment by marcingrzejszczak** [comment]
Done via https://github.com/spring-cloud/spring-cloud-release-tools/commit/e7fffd37ba4bad5f7faffe40b12ec56ff7bf05b8
